---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
    app.quarkus.io/commit-id: 4f3a0cab887acc97f301a8c6614fa32ee8f4d7de
    app.quarkus.io/vcs-uri: https://github.com/Jojoooo1/operator-sdk.git
    app.quarkus.io/build-timestamp: 2024-07-25 - 12:58:05 +0000
  labels:
    app.kubernetes.io/name: ns-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: ns-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-reconciler-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - namespaces/status
      - namespaces/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - ""
    resources:
      - limitranges
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    app.dekorate.io/commit-id: 4f3a0cab887acc97f301a8c6614fa32ee8f4d7de
  name: josdk-crd-validating-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reconciler-crd-validating-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: ns-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-reconciler-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: ns-operator
subjects:
  - kind: ServiceAccount
    name: ns-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ns-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: ns-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: ns-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
    app.quarkus.io/commit-id: 4f3a0cab887acc97f301a8c6614fa32ee8f4d7de
    app.quarkus.io/vcs-uri: https://github.com/Jojoooo1/operator-sdk.git
    app.quarkus.io/build-timestamp: 2024-07-25 - 12:58:05 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: ns-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: ns-operator
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ns-operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
    app.quarkus.io/commit-id: 4f3a0cab887acc97f301a8c6614fa32ee8f4d7de
    app.quarkus.io/vcs-uri: https://github.com/Jojoooo1/operator-sdk.git
    app.quarkus.io/build-timestamp: 2024-07-25 - 12:58:05 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: ns-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: ns-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ns-operator
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.11.0
        app.quarkus.io/commit-id: 4f3a0cab887acc97f301a8c6614fa32ee8f4d7de
        app.quarkus.io/vcs-uri: https://github.com/Jojoooo1/operator-sdk.git
        app.quarkus.io/build-timestamp: 2024-07-25 - 12:58:05 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: ns-operator
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/jonathan/akuity-ns-operator:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: ns-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: ns-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
    app.quarkus.io/commit-id: 4f3a0cab887acc97f301a8c6614fa32ee8f4d7de
    app.quarkus.io/vcs-uri: https://github.com/Jojoooo1/operator-sdk.git
    app.quarkus.io/build-timestamp: 2024-07-25 - 12:58:05 +0000
  labels:
    app.kubernetes.io/name: ns-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: ns-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ns-operator
  endpoints:
    - scheme: http
      targetPort: 8080
      path: /q/metrics
      interval: 10s
      honorLabels: true
