name: "run tests"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ develop ]

concurrency:
  group: ci-dev-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'maven'
      
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.13.0
        with:
          minikube version: v1.33.0
          kubernetes version: v1.33.1
          driver: 'docker'
          github token: ${{ secrets.GITHUB_TOKEN }}
      
      # 2. Run tests
      - name: Run Unit & Integration Tests
        run: mvn clean verify --no-transfer-progress